#-- BASE DEL PROYECTO DATABASE --#
  development:
    adapter: mysql2
    encoding: utf8
    database: proyecto-base
    username: root
    password: root
    host: 127.0.0.1
    port: 3306
#    
  test:
    adapter: mysql2
    encoding: utf8
    database: proyecto-base
    username: root
    password: root
    host: 127.0.0.1
    port: 3306
#    
  production:
    adapter: mysql2
    encoding: utf8
    database: proyecto-base
    username: root
    password: root
    host: 127.0.0.1
    port: 3306

#-- BASE GLOBAL --#

  global_development:
    adapter: mysql2
    encoding: utf8
    database: global
    username: root
    password: root
    host: 172.16.0.15
    port: 3306
#    
  global_test:
    adapter: mysql2
    encoding: utf8
    database: global
    username: root
    password: root
    host: 172.16.0.15
    port: 3306
#    
  global_production:
    adapter: mysql2
    encoding: utf8
    database: global
    username: root
    password: root
    host: 172.16.0.15
    port: 3306
